### ISSUE TITLE
S3 einrichten

### ISSUE THREAD

**Issue by Kexikus** [Kexikus/SWU_Epiphany#52]

**Comment by SWUChristoph** [comment]
Okay, S3 ist auf der neuen Staging-Seite konfiguriert und tut, was es tun soll. 
Ich habe mal das Titelbild des TOTJ-Specials ersetzt zu https://swuimagestorage.s3.eu-central-1.amazonaws.com/2024/10/Tales-of-the-Jedi-Cover-Art-980x551.jpg, d.h. man sieht dort jetzt ziemlich gut die Unterschiede in der Ladezeit. Die faktisch 0 betragen, soweit ich es sagen kann, seit der Server auf Frankfurt umgestellt ist.
MP4s hab ich auch ausprobiert, da kann ich auch keine Probleme erkennen.

Ich behaupte also, Du kannst den Kram mergen, Markus, und dann widmen wir uns den anderen Baustellen.
