### ISSUE TITLE
News/Artikel oben gehalten verschwunden

### ISSUE THREAD

**Issue by SWUChristoph** [Kexikus/SWU_Epiphany#54]
![Bildschirmfoto 2024-12-03 um 09 34 41](https://github.com/user-attachments/assets/320563bd-db0b-4011-a206-f2c3bbe8a225)
Hier war mal ein Häkchen-Feld, über das man das „Empfohlen”-Feature auf der Startseite aktivieren und deaktivieren konnte. Das ist ca. im September verschwunden.

**Comment by Kexikus** [comment]
Das ist jetzt unter "Status" zu finden
![grafik](https://github.com/user-attachments/assets/a4c8a425-e07d-4376-bbc5-1d9446de1064)
